version: "3.9"

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile.dev
    volumes:
      - ./front_end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend    



  backend:
    build: ./back_end
    volumes:
      - ./back_end:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
